### PR TITLE
feat(ui): add devalue-parser as parser option

### PR DESCRIPTION
**Pull request by rChaoz**
This PR adds the new socket.io [devalue-parser](https://github.com/socketio/socket.io-devalue-parser) as an option for the admin UI.

The `ui/dist` directory was built using the `Dockerfile`.

### CODE REVIEW

**Comment by rChaoz** [comment]
Doesn't actually work due to extremely old npm/node/libraries

**Comment by darrachequesne** [comment]
Yes, we definitely need to upgrade to vue3/node20...

**Comment by rChaoz** [comment]
@darrachequesne I think at this point it's better to create a Vue project from scratch, add all the libraries and drop the source code into it.

If you think that's a good approach, should I give it a go?

**Comment by darrachequesne** [comment]
@rChaoz that would be awesome :+1:

**Pull request closed without merging**
